apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2025-12-24T14:55:56Z"
  name: default
  namespace: sample-spring-kafka-microservices
  resourceVersion: "496"
  uid: b308fa06-f9f3-49cf-aca3-c21031f232ac
