apiVersion: v1
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDBjCCAe6gAwIBAgIHVqktCMxHCzANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQD
    EwprdWJlcm5ldGVzMCAXDTI1MTIyNDA1MjUxOVoYDzIxMjUxMTMwMDUzMDE5WjAV
    MRMwEQYDVQQDEwprdWJlcm5ldGVzMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
    CgKCAQEAsJ4uLpDU7dfEVeMSKHuIgtqruyCx/VFNfFOJSEO4vZpLUuYwXyz60zjV
    reIYC8Ed06tmIUIawf1J5z1cC4ITRcV1khKDVm6m/VqYRQiq/EGLfZbdkhmblPIh
    i6WzTFW+wCeO4x7YdEP96LB0qQVUpsZJrgHyAoM6sNBFgrEw/yoqO8rG2L0567JX
    2Zx2CwmIdpZqoZU3CsFjPeogqPHPVHktPr0aYG8nInNuyMVneOY1yW0BQlqscASi
    LBah6S0ik1ehbtnUEQIman3CB8l6HkPszGGH8X88AOZHfnv4G3QDDBzJWXRKcmPt
    zR9DzONZAu+yBylaFAy0KzJxNwfN7wIDAQABo1kwVzAOBgNVHQ8BAf8EBAMCAqQw
    DwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUNetZl3vq8E6f1XC6Jgfr/wjo3xQw
    FQYDVR0RBA4wDIIKa3ViZXJuZXRlczANBgkqhkiG9w0BAQsFAAOCAQEAmT+Pq+5t
    j7o7YfEIvoFsW4uEu5CKOVOCuiHiTFmi2AGF0U0kN3l0nodrUqvn3wmvObRuWT9F
    Y0dFFjdXa9qhOptQha8HOWbus+GSf/thD+lrkOxh994JX8aRaXw5Dinc5xXz1DjJ
    Lj8f6DI4JBdEkVpMGvJ2Dh3SL+n6VgI6p9rjJp2+qrhF6R8jaucy1F/MXkpj+hrG
    hsMzA7LErfTRMSPP7oKy5iTeaqACbE19TGE2xQGN0wiAeGRWNGb5abvsr7EaPElD
    BesFM9HXOdC0Ol9WFdEm8uPSM8R7oQxMKvmmMAZ34MMJRDEpBo2pDvzjwrXUjKtd
    /noeuffSsT5FgQ==
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  annotations:
    kubernetes.io/description: Contains a CA bundle that can be used to verify the
      kube-apiserver when using internal endpoints such as the internal service IP
      or kubernetes.default.svc. No other usage is guaranteed across distributions
      of Kubernetes clusters.
  creationTimestamp: "2025-12-24T14:55:56Z"
  name: kube-root-ca.crt
  namespace: sample-spring-kafka-microservices
  resourceVersion: "495"
  uid: 9fadeca3-6f3a-4274-9a17-d5276ddd71ba
